random_search:
  class: RandomizedSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      max_depth: 5
      min_samples_leaf: 2
      min_samples_split: 2
      n_estimators: 500
    search_param_random:
      min_samples_leaf:
        - 6